# Generated by Django 2.0.4 on 2018-04-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_abbr', models.CharField(max_length=5)),
                ('company', models.CharField(max_length=128)),
                ('director', models.CharField(blank=True, max_length=64, null=True)),
                ('relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('stock_type', models.CharField(max_length=64)),
                ('doc_date', models.DateField()),
                ('received_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=64)),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
