# Generated by Django 2.0.4 on 2018-05-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawdata',
            options={'ordering': ['received_date']},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-latest']},
        ),
    ]
