# Generated by Django 2.1.1 on 2018-09-23 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20180520_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterStock',
            fields=[
                ('stock_abbr', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='company',
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='stock_abbr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.MasterStock'),
        ),
    ]
