# Generated by Django 2.1.1 on 2018-09-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_auto_20180923_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterstock',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
